## Used to test Herbie install from PyPI

name: herbie-test
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - pip

  #==============
  # Dependencies
  #==============
  - cartopy>=0.20.3
  - cfgrib>=0.9.10.1
  - matplotlib>=3.5.3
  - metpy
  - numpy
  - pandas
  - pygrib
  - pytest
  - requests
  - toml
  - xarray>=2022.6.0

  #====================
  # Other Dependencies
  #====================
  - curl
  - eccodes # required by cfgrib
  - geos # required by cartopy
  - proj # required by cartopy
