name: Lint with Black

on:
  #push:
  #  branches: [main]
  #pull_request:
  #  branches: [main]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
